"""Metadados dos conjuntos prioritários para anp-fuel-analytics (geração de docs)."""
from __future__ import annotations

CONJUNTOS_FUEL = [
    {
        "num": 21,
        "slug": "movimentacao-derivados",
        "title": "Movimentação de derivados de petróleo, gás natural e biocombustíveis",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/dados-abertos-movimentacao-de-derivados-de-petroleo",
        "unidade": "SDL",
        "periodicidade": "Mensal",
        "formato": "CSV / ZIP (por produto)",
        "fonte": "SIMP — Resolução ANP nº 729/2018",
        "contexto": "Divulga volumes movimentados pelos agentes regulados, segmentados por produto (combustíveis líquidos, GLP, lubrificantes, TRR, etc.), com proteção de informações sigilosas conforme a resolução.",
        "relevancia": "Núcleo analítico do abastecimento: volumes por agente, produto e fluxo logístico. Complementa tancagem (capacidade) com movimentação real.",
        "cruzamentos": ["tancagem-abastecimento", "cadastro-revendas-combustiveis", "vendas-derivados", "serie-historica-precos"],
        "inventario": "Movimentação de Derivados… (várias sub-bases por produto)",
    },
    {
        "num": 12,
        "slug": "cadastro-revendas-combustiveis",
        "title": "Dados Cadastrais dos Revendedores Varejistas de Combustíveis Automotivos",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/dados-cadastrais-dos-revendedores-varejistas-de-combustiveis-automotivos",
        "unidade": "SDL",
        "periodicidade": "Diária",
        "formato": "CSV",
        "fonte": "Cadastro ANP / i-SIMP",
        "contexto": "Cadastro de postos revendedores de combustíveis automotivos (localização, bandeira, situação cadastral).",
        "relevancia": "Geografia do varejo e cruzamento com tancagem, preços e movimentação por município/UF.",
        "cruzamentos": ["tancagem-abastecimento", "pontos-abastecimento", "serie-historica-precos", "movimentacao-derivados"],
        "inventario": "Dados Cadastrais dos Revendedores Varejistas de Combustíveis Automotivos",
    },
    {
        "num": 11,
        "slug": "cadastro-revendas-glp",
        "title": "Dados Cadastrais das Revendas de Gás Liquefeito de Petróleo (GLP)",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/dados-cadastrais-das-revendas-de-gas-liquefeito-de-petroleo",
        "unidade": "SDL",
        "periodicidade": "Diária",
        "formato": "CSV",
        "fonte": "Cadastro ANP",
        "contexto": "Cadastro de revendas de GLP (botijão e granel), com localização e situação.",
        "relevancia": "Mercado de gás engarrafado; complementa movimentação GLP e tancagem por grupo de produtos.",
        "cruzamentos": ["movimentacao-derivados", "tancagem-abastecimento"],
        "inventario": "Dados Cadastrais das Revendas de Gás Liquefeito de Petróleo",
    },
    {
        "num": 27,
        "slug": "pontos-abastecimento",
        "title": "Pontos de Abastecimento Autorizados",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/pontos-de-abastecimento-autorizados",
        "unidade": "SDL",
        "periodicidade": "Diário",
        "formato": "CSV",
        "fonte": "Cadastro ANP",
        "contexto": "Instalações de pontos de abastecimento autorizados (estrutura cadastral distinta do revendedor varejista).",
        "relevancia": "Infraestrutura autorizada de abastecimento; cruzamento com cadastro de revendas e fiscalização.",
        "cruzamentos": ["cadastro-revendas-combustiveis", "fiscalizacao-abastecimento"],
        "inventario": "Dados Cadastrais de Pontos de Abastecimento Autorizados",
    },
    {
        "num": 15,
        "slug": "distribuidores-combustiveis-liquidos",
        "title": "Distribuidores de combustíveis líquidos",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/dados-abertos-distribuidores-de-combustiveis-liquidos",
        "unidade": "SDL",
        "periodicidade": "Mensal / Semanal / Semestral (subconjuntos)",
        "formato": "CSV",
        "fonte": "Cadastro e autorizações ANP",
        "contexto": "Distribuidores autorizados, contratos de cessão, inutilizadores de botijões GLP e início de atividade.",
        "relevancia": "Atacado/distribuição — elos entre refinaria/terminal e varejo.",
        "cruzamentos": ["movimentacao-derivados", "capacidade-armazenagem-terminais"],
        "inventario": "Distribuidores de Combustíveis Líquidos (várias bases)",
    },
    {
        "num": 28,
        "slug": "pmqc",
        "title": "Programa de Monitoramento da Qualidade dos Combustíveis (PMQC)",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/pmqc-programa-de-monitoramento-da-qualidade-dos-combustiveis",
        "unidade": "SBQ",
        "periodicidade": "Mensal",
        "formato": "CSV / relatórios",
        "fonte": "PMQC / fiscalização analítica",
        "contexto": "Indicadores de qualidade dos combustíveis comercializados e focos de não conformidade.",
        "relevancia": "Qualidade regulatória; contexto para anomalias em séries de preço ou movimentação.",
        "cruzamentos": ["fiscalizacao-abastecimento", "cadastro-revendas-combustiveis"],
        "inventario": "PMQC — Programa de Monitoramento da Qualidade dos Combustíveis",
    },
    {
        "num": 29,
        "slug": "pml",
        "title": "Programa de Monitoramento dos Lubrificantes (PML)",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/o-programa-de-monitoramento-dos-lubrificantes-pml",
        "unidade": "SBQ",
        "periodicidade": "Conforme programa",
        "formato": "CSV / relatórios",
        "fonte": "PML",
        "contexto": "Monitoramento da qualidade de lubrificantes no mercado.",
        "relevancia": "Segmento lubrificantes; complementa movimentação de lubrificantes e registro de produtos.",
        "cruzamentos": ["movimentacao-derivados", "registro-lubrificantes"],
        "inventario": "Programa de Monitoramento dos Lubrificantes",
    },
    {
        "num": 40,
        "slug": "serie-historica-precos",
        "title": "Série Histórica de Preços de Combustíveis",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/serie-historica-de-precos-de-combustiveis",
        "unidade": "SDC",
        "periodicidade": "Semanal (LPC) — agregações mensais/semestrais nos arquivos abertos",
        "formato": "CSV",
        "fonte": "Levantamento de Preços de Combustíveis (LPC)",
        "contexto": "Preços medios de revenda/distribuição por localidade (gasolina C, etanol, diesel, GNV, GLP P13).",
        "relevancia": "Série temporal de preços para cruzar com tancagem regional, movimentação e eventos de mercado.",
        "cruzamentos": ["vendas-derivados", "cadastro-revendas-combustiveis", "tancagem-abastecimento"],
        "inventario": "Série Histórica Preços — Combustíveis automotivos / GLP",
    },
    {
        "num": 42,
        "slug": "vendas-derivados",
        "title": "Vendas de derivados de petróleo e biocombustíveis",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/vendas-de-derivados-de-petroleo-e-biocombustiveis",
        "unidade": "SDC",
        "periodicidade": "Mensal / Anual (subconjuntos)",
        "formato": "CSV",
        "fonte": "Estatística ANP / distribuidoras",
        "contexto": "Volumes vendidos por distribuidoras, segmento, tipo de produto e recorte geográfico (estado/município).",
        "relevancia": "Demanda aparente por produto e região; complementa movimentação e produção.",
        "cruzamentos": ["movimentacao-derivados", "producao-biocombustiveis", "importacoes-exportacoes"],
        "inventario": "Vendas de combustíveis por segmento / por tipo / vendas anuais por município",
    },
    {
        "num": 2,
        "slug": "fiscalizacao-abastecimento",
        "title": "Ações de Fiscalização do Abastecimento",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/acoes-de-fiscalizacao",
        "unidade": "SFI",
        "periodicidade": "Mensal",
        "formato": "CSV / painéis",
        "fonte": "Fiscalização ANP",
        "contexto": "Ações de fiscalização nos segmentos do abastecimento (documentos, agentes, resultados).",
        "relevancia": "Contexto regulatório e qualidade de mercado; alguns recortes só em painel dinâmico.",
        "cruzamentos": ["pmqc", "cadastro-revendas-combustiveis"],
        "inventario": "Ações de Fiscalização do Abastecimento",
    },
    {
        "num": 9,
        "slug": "capacidade-armazenagem-terminais",
        "title": "Capacidade de Armazenagem de Terminais",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/capacidade-de-armazenagem-de-terminais",
        "unidade": "SIM",
        "periodicidade": "Semestral",
        "formato": "CSV",
        "fonte": "Cadastro de terminais ANP",
        "contexto": "Capacidade de armazenagem de terminais (fluvial, lacustre, marítimo, terrestre) por empresa e local.",
        "relevancia": "Infra logística upstream do abastecimento; validação cruzada com tancagem (escopos diferentes).",
        "cruzamentos": ["tancagem-abastecimento", "movimentacao-terminais-aquaviarios"],
        "inventario": "Capacidade de armazenamento dos terminais…",
    },
    {
        "num": 22,
        "slug": "movimentacao-terminais-aquaviarios",
        "title": "Movimentação dos Terminais Aquaviários",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/movimentacao-dos-terminais-aquaviarios",
        "unidade": "SIM",
        "periodicidade": "Mensal",
        "formato": "CSV",
        "fonte": "Terminais aquaviários",
        "contexto": "Movimentação em terminais aquaviários autorizados.",
        "relevancia": "Fluxo logístico costeiro/fluvial de derivados; complementa capacidade de terminais.",
        "cruzamentos": ["capacidade-armazenagem-terminais", "movimentacao-derivados"],
        "inventario": "Movimentação dos Terminais Aquaviários",
    },
    {
        "num": 37,
        "slug": "registro-lubrificantes",
        "title": "Registro de Óleos e Graxas Lubrificantes",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/registro-de-oleos-e-graxas-lubrificantes",
        "unidade": "SDL",
        "periodicidade": "Conforme demanda",
        "formato": "CSV",
        "fonte": "Registro de produtos",
        "contexto": "Produtos lubrificantes registrados na ANP.",
        "relevancia": "Catálogo de produtos; cruzamento com PML e movimentação de lubrificantes.",
        "cruzamentos": ["pml", "movimentacao-derivados"],
        "inventario": "Registro de Óleos e Graxas Lubrificantes",
    },
    {
        "num": 32,
        "slug": "processamento-petroleo-derivados",
        "title": "Processamento de petróleo e produção de derivados",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/processamento-de-petroleo-e-producao-de-derivados",
        "unidade": "SDC",
        "periodicidade": "Mensal",
        "formato": "CSV",
        "fonte": "Estatística de refino ANP",
        "contexto": "Processamento de petróleo e produção de derivados por refinaria e tipo de produto.",
        "relevancia": "Oferta doméstica de derivados — contexto macro para abastecimento e vendas.",
        "cruzamentos": ["vendas-derivados", "importacoes-exportacoes"],
        "inventario": "Processamento de petróleo e produção de derivados (várias tabelas)",
    },
    {
        "num": 33,
        "slug": "producao-biocombustiveis",
        "title": "Produção de biocombustíveis",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/producao-de-biocombustiveis",
        "unidade": "SDC",
        "periodicidade": "Mensal",
        "formato": "CSV",
        "fonte": "Estatística ANP",
        "contexto": "Produção de biodiesel e etanol (séries por período e região).",
        "relevancia": "Oferta de etanol/biodiesel no mix de abastecimento.",
        "cruzamentos": ["vendas-derivados", "movimentacao-derivados", "serie-historica-precos"],
        "inventario": "Produção de Biocombustíveis — biodiesel / etanol",
    },
    {
        "num": 34,
        "slug": "producao-por-estado",
        "title": "Produção de petróleo e gás natural por estado e localização",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/producao-de-petroleo-e-gas-natural-por-estado-e-localizacao",
        "unidade": "SDC / SDP",
        "periodicidade": "Mensal",
        "formato": "CSV",
        "fonte": "E&P / estatística ANP",
        "contexto": "Produção de petróleo, LGN e gás por UF e tipo de localização (terra/mar).",
        "relevancia": "Contexto upstream; normalizações per capita ou por capacidade de abastecimento.",
        "cruzamentos": ["importacoes-exportacoes", "anuario-estatistico"],
        "inventario": "Produção de Petróleo e Gás Natural por Estado e Localização",
    },
    {
        "num": 35,
        "slug": "producao-por-poco",
        "title": "Produção de Petróleo e Gás Natural por Poço",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/producao-de-petroleo-e-gas-natural-por-poco",
        "unidade": "SDP",
        "periodicidade": "Mensal / Anual (séries históricas)",
        "formato": "CSV",
        "fonte": "E&P",
        "contexto": "Produção detalhada por poço (séries recentes e históricas).",
        "relevancia": "Granularidade fina de upstream; uso indireto em estudos de abastecimento regional.",
        "cruzamentos": ["producao-por-estado"],
        "inventario": "Produção de Petróleo e Gás Natural por Poço",
    },
    {
        "num": 19,
        "slug": "importacoes-exportacoes",
        "title": "Importações e exportações",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/importacoes-e-exportacoes",
        "unidade": "SDC",
        "periodicidade": "Mensal",
        "formato": "CSV",
        "fonte": "Estatística ANP / comércio exterior",
        "contexto": "Importações e exportações de petróleo, derivados e etanol.",
        "relevancia": "Balanço oferta externa de combustíveis e derivados.",
        "cruzamentos": ["vendas-derivados", "processamento-petroleo-derivados"],
        "inventario": "Importações e exportações de petróleo / derivados / etanol",
    },
    {
        "num": 5,
        "slug": "anuario-estatistico",
        "title": "Anuário Estatístico Brasileiro do Petróleo, Gás Natural e Biocombustíveis",
        "url": "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/anuario-estatistico-brasileiro-do-petroleo-gas-natural-e-biocombustiveis",
        "unidade": "SDC",
        "periodicidade": "Anual (tabelas históricas ~10 anos)",
        "formato": "CSV",
        "fonte": "Consolidação estatística ANP",
        "contexto": "Consolida desempenho da indústria e do abastecimento em dezenas de tabelas CSV.",
        "relevancia": "Visão macro longa para validar séries mensais e benchmarks nacionais.",
        "cruzamentos": ["vendas-derivados", "producao-biocombustiveis", "importacoes-exportacoes"],
        "inventario": "Anuário Estatístico",
    },
]
